### ISSUE TITLE
How to build with datomic pro ?

### ISSUE THREAD

**Issue by lenw** [plexus/metabase-datomic#1]
I have added 

` :mvn/repos  {"my.datomic.com" {:url "https://my.datomic.com/repo"}}`

and added my cedentials to `~/.m2/settings.xml `

but when I run `lein with-profiles +datomic-pro uberjar `

I get 

```
Could not find artifact com.datomic:datomic-pro:jar:0.9.5561.62 in central (https://repo1.maven.org/maven2/)
Could not find artifact com.datomic:datomic-pro:jar:0.9.5561.62 in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Uberjar aborting because jar failed: Could not resolve dependencies
Error encountered performing task 'uberjar' with profile(s): 'base,system,user,provided,dev,datomic-pro'
Uberjar aborting because jar failed: Could not resolve dependencies
```

Whats the right way to get the datomic-pro plugin working ?

**Comment by plexus** [comment]
Hi Len,

The build path for pro is as of yet untested, there are several things that could still be wrong with it. If you figure it out do submit a PR!

**Comment by lenw** [comment]
I added this to the `project.clj`

```
:repositories
  {"my.datomic.com" {:url "https://my.datomic.com/repo"}}
```

And added this to `deps.edn`

```
 :mvn/repos
        {
         "my.datomic.com" {:url "https://my.datomic.com/repo"}
         }
```
and added my credentials into `~.m2/settings.xml` 

Not sure why but I had to have both to get it to compile. Will test and see if it works.

**Comment by plexus** [comment]
Thanks, I've added the repos to project.clj and deps.edn.
