### ISSUE TITLE
Problem to connect an in-memory database

### ISSUE THREAD

**Issue by wandersoncferreira** [plexus/metabase-datomic#7]
Hi,

I am trying to connect to my in-memory database but I keep receiving the following error:

`{:message "Unable to connect to database."}`

It's possible to use with an in-memory db?

**Comment by plexus** [comment]
Yes, but only if the in-memory db is created inside the Metabase process. You can't connect to an in-memory db in another JVM.

**Comment by wandersoncferreira** [comment]
Okay, I got it. Thanks
